"""
Shared constants.
"""

DEFAULT_LOG_LEVEL = 'INFO'

REQUIRED_ENV = []

_SEC_PER_MIN = 60
_MIN_PER_HOUR = 60
SEC_PER_HOUR = _SEC_PER_MIN * _MIN_PER_HOUR

DEFAULT_FOUNDATIONS_JSON = 'foundations.json'
DEFAULT_QUERIES_FILE = 'metricQueries.json'
DEFAULT_INFLUX_DATABASE = 'cf-stats'
DEFAULT_INFLUX_HOST = 'influxdb-poc01.unix.gsm1900.org'
DEFAULT_INFLUX_PORT = 8086
DEFAULT_INFLUX_TIMEOUT = 10

DEFAULT_DATADOG_TIME_RANGE = 75
DEFAULT_START_TIMESTAMP = 1479945600 #11/23/2016 12:00 am

OVERRIDABLE_ENV = {
        'LOG_LEVEL': DEFAULT_LOG_LEVEL,
        'DATADOG_TIME_RANGE': DEFAULT_DATADOG_TIME_RANGE,
        'START_TIMESTAMP': DEFAULT_START_TIMESTAMP,
        'QUERIES_FILE': DEFAULT_QUERIES_FILE,
        'INFLUX_DATABASE': DEFAULT_INFLUX_DATABASE,
        'INFLUX_HOST': DEFAULT_INFLUX_HOST,
        'INFLUX_PORT': DEFAULT_INFLUX_PORT,
        'INFLUX_USER': '',
        'INFLUX_PASSWORD': '',
        'INFLUX_TIMEOUT': DEFAULT_INFLUX_TIMEOUT,
        'DATADOG_API_KEY': None,
        'DATADOG_APP_KEY': None,
}
